server:
  port: 8761

eureka:
  instance:
    nonSecurePort: ${server.port}
    instanceId: eureka:${spring.application.instance-id:${random.value}}
    preferIpAddress: false
  client:
    enabled: true
    registerWithEureka: false
    fetchRegistry: true
  metadataMap:
    user: uservice
    password: password

